we

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -23,21 +23,26 @@ jobs:
     steps:
         - name: Check out code
           uses: actions/checkout@v3
-
+        - name: Verify CSV exists
+          run: |
+            if [ ! -f "./05_overall/05_fcs_dimensioning_model/Postprocessing/test_data/optimized_parameters_25-150kW_400-500_100-100ft.csv" ]; then
+              echo "CSV not found!"
+              exit 1
+            fi
         # 2. Miniconda installieren
-        - name: Set up Miniconda
-          uses: conda-incubator/setup-miniconda@v2
-          with:
-            auto-update-conda: true
-            python-version: 3.9
+        #- name: Set up Miniconda
+        #  uses: conda-incubator/setup-miniconda@v2
+        #  with:
+        #    auto-update-conda: true
+        #    python-version: 3.9
 
-        - name: Create Conda environment
-          run: |
-            conda env create --file ./05_overall/05_fcs_dimensioning_model/conda_env.yaml --name conda_env
+        #- name: Create Conda environment
+        #  run: |
+        #    conda env create --file ./05_overall/05_fcs_dimensioning_model/conda_env.yaml --name conda_env
 
-        - name: Activate and test Conda environment
-          run: |
-            conda activate conda_env
+        #- name: Activate and test Conda environment
+        #  run: |
+        #    conda activate conda_env
 
         - name: Run test Python file
           run: conda run -n conda_env python ./05_overall/05_fcs_dimensioning_model/Postprocessing/get_plots.py
